#10 feat : [카드상세] 카드 댓글 달기
JamminTeam/Jamrello pull request #30
Opened 2023-12-27 07:25 UTC by JungHyunMoon

카드 댓글 작성 createCard 구현
test : teatCode
controller, service, entity 테스트 코드 작성

다음에는 test용 브랜치 따서 하겠습니다..!

2023-12-27 07:33 UTC, dmlal approved these changes
👍 👍 👍  수고하셨습니다!

2023-12-27 07:46 UTC, wonowonow requested changes
테스트 코드까지 작성해주시느라 수고 많으셨습니다!
제가 남겨드린 코멘트 부분 수정 부탁드립니다~

2023-12-27 07:46 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/comment/controller/CommentController.java
> +        return ResponseEntity.ok(response);
return 할 때
ResponseEntity.status(HttpStatus.OK).body(BaseResponse.of(ResponseCode.CREATED_COMMENT, comment))
이렇게 하는 건 어떨까요?

2023-12-27 07:46 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/comment/dto/CommentRequestDto.java
> +    public Comment toEntity(Member member, Card card) {
toEntity 같은 메서드의 경우 저희 팩토리 패턴 쓰기로 했으니까 Entity 내부로 정적 메서드로 이동하는 게 좋을 거 같아요!

2023-12-27 07:46 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/comment/dto/CommentRequestDto.java
> +    public Comment toEntity(Member member, Card card) {
조금 더 의미있는 이름이었으면 좋겠어요 예를 들면 createComment?

2023-12-28 09:24 UTC, JungHyunMoon commented on src/main/java/com/sparta/jamrello/domain/comment/controller/CommentController.java
> +        return ResponseEntity.ok(response);
완료했습니다!

2023-12-28 09:24 UTC, JungHyunMoon commented on src/main/java/com/sparta/jamrello/domain/comment/dto/CommentRequestDto.java
> +    public Comment toEntity(Member member, Card card) {
완료했습니다!

2023-12-28 11:25 UTC, zomeong commented on src/main/java/com/sparta/jamrello/domain/comment/controller/CommentController.java
> +    @PostMapping("/cards/{cardId}/comment")
card api가 /api/boards/{boardId}/catalogs/{catalogId}/cards라서 comment도 이 경로의 하위에 들어가야하지 않을까요??

2023-12-28 11:26 UTC, zomeong reviewed
고생하셨습니다👍

2023-12-28 13:58 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/comment/controller/CommentController.java
> +            commentService.updateComment(commentId, member, commentRequestDto));
추후에 토큰에서 유저 정보를 가져온다는 기능이 개발 된다면, 서비스 매개변수에 member를 직접 넣는다기 보다는
member.getId로 넣어주는 게 수정이 덜 되고 좋을 거 같습니다

2023-12-29 02:59 UTC, wonowonow requested changes

2023-12-29 02:59 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/comment/controller/CommentController.java
> +    private final CommentServiceImplV1 commentServiceImplV1;
구현체를 주입 받는 것보다는 인터페이스를 주입 받고 구현체 우선 순위를 지정해주는 게 좋을 거 같습니다
https://wonowdaily.tistory.com/78

2023-12-29 02:59 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/comment/controller/CommentController.java
> +        commentServiceImplV1.deleteComment(commentId, member);
멤버 아이디로 넣어주세요!

2023-12-29 05:14 UTC, wonowonow approved these changes
수고하셨습니다!

2023-12-29 05:14 UTC, merged