Feature/card
JamminTeam/Jamrello pull request #34
Opened 2023-12-28 04:46 UTC by zomeong

2023-12-28 05:21 UTC, wonowonow requested changes
테스트 코드까지 작성해주시느라 수고하셨습니다. 제가 코멘트 남긴 부분 수정 부탁드립니다!
혹시라도 제가 틀린 부분이 있을 수 있어서, 다르게 생각하시면 얘기 나눠보죠

2023-12-28 05:21 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/member/repository/entity/Member.java
> +    @OneToMany(mappedBy = "member", cascade = CascadeType.ALL, orphanRemoval = true)
멤버에서 카드를 갖고 있는 이유가 궁금합니다.
저희 ERD에서는 멤버에서 카드를 따로 갖지 않고 멤버 조회가 가능한데요
이 부분 수정해주셨으면 합니다

2023-12-28 05:21 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/member/repository/entity/Member.java
> +    @OneToMany(mappedBy = "member", cascade = CascadeType.ALL, orphanRemoval = true)
![image](https://github.com/JamminTeam/Jamrello/assets/123870616/21c99e9e-ade1-4049-993e-f1b34e4e21a8)

2023-12-28 05:21 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/card/Service/CardServiceImplV1.java
> +        cardRepository.save(card);
카탈로그에서 카드를 갖고 있는데 따로 연관관계 메소드를 사용하는 부분이 안 보입니다.
이러면 DB상에서는 알고 있지만, 자바에서는 카탈로그에 있는 카드 리스트에 아무 것도 안 넣어지지 않을까요?

2023-12-28 05:21 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/card/dto/response/CardResponseDto.java
> +public record CardResponseDto(
카드를 불러올 때 추가적으로 어떤 정보가 필요할까요?
현재 보드에서 getBoard 메서드를 사용했을 때, 카탈로그랑 카드(이미지, 내용, 댓글 수 등등)를 한번에 불러오는 메소드로 하려고 하는데요
카드의 modified를 제외한 정보들과 댓글 정보까지 반환을 하면 좋겠습니다.

2023-12-28 05:21 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/card/repository/entity/Card.java
position 필드가 없습니다

2023-12-28 05:21 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/card/Service/CardServiceImplV1.java
> +            BaseResponse.of(ResponseCode.CREATED_CARD, new CardResponseDto(card.getTitle()))
서비스까지 ResponseEntity를 끌고와서 사용하시는 이유가 있으실까요?
서비스 레이어는 비즈니스 로직만을 담당하고, 컨트롤러 레이어는 응답 반환만을 담당하게
즉 책임 분리 원칙을 지켰으면 좋겠는데, 이 부분에 대해서 어떻게 생각하시나요?

2023-12-28 05:21 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/card/dto/request/CardRequestDto.java
> +    public CardRequestDto(String title) {
이 생성자는 어떤 필요에 의해서 만드신 건가요?
RequestDto에서 값을 받을 때, json에 아무 값도 안 넣으면 Record 클래스 생성자에서 자동으로 필드 null 값을 넣는 걸로 알고 있는데, 이 생성자를 왜 만드신 건지 궁금합니다.

2023-12-28 05:21 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/card/dto/request/CardRequestDto.java
> +    public CardRequestDto(String title) {
제가 잘못 알고 있는 걸수도 있습니다....

2023-12-28 06:13 UTC, zomeong commented on src/main/java/com/sparta/jamrello/domain/member/repository/entity/Member.java
> +    @OneToMany(mappedBy = "member", cascade = CascadeType.ALL, orphanRemoval = true)
네 수정하도록 하겠습니다!

2023-12-28 06:14 UTC, zomeong commented on src/main/java/com/sparta/jamrello/domain/card/Service/CardServiceImplV1.java
> +        cardRepository.save(card);
연관관계 매핑해두면 따로 메소드를 사용하지 않아도 카드 리스트에 자동으로 추가되는 것으로 알고 있어요 정확한지에 대해 저도 다시 알아보도록 하겠습니다

2023-12-28 06:15 UTC, dmlal approved these changes
👍 👍

2023-12-28 06:16 UTC, zomeong commented on src/main/java/com/sparta/jamrello/domain/card/dto/response/CardResponseDto.java
> +public record CardResponseDto(
네 추가하도록 하겠습니다!

2023-12-28 06:18 UTC, zomeong commented on src/main/java/com/sparta/jamrello/domain/card/Service/CardServiceImplV1.java
> +            BaseResponse.of(ResponseCode.CREATED_CARD, new CardResponseDto(card.getTitle()))
컨트롤러의 로직을 간단하게 하려다보니 이러한 방식으로 사용했었는데 분리하는 것이 책임 분리 원칙을 따를 수 있겠네요! 수정하도록 하겠습니다

2023-12-28 06:19 UTC, zomeong commented on src/main/java/com/sparta/jamrello/domain/card/dto/request/CardRequestDto.java
> +    public CardRequestDto(String title) {
record 사용이 처음이라 에러가 발생하는 것을 보고 생성자를 만들었는데 null 값을 넣으면 되는군요 이 부분도 수정하겠습니다~

2023-12-29 13:39 UTC, JungHyunMoon approved these changes
수정하느라 수고 많으셨습니다!!!
![image](https://github.com/JamminTeam/Jamrello/assets/120004247/d06d20b5-31e5-48ec-9f61-14380352f769)

2023-12-29 13:51 UTC, wonowonow approved these changes
![image](https://github.com/JamminTeam/Jamrello/assets/123870616/eef02f90-4fc9-42e9-9227-85f6b121d949)

2023-12-29 13:52 UTC, merged