Test/card detail
JamminTeam/Jamrello pull request #37
Opened 2023-12-28 09:23 UTC by JungHyunMoon

2023-12-28 14:39 UTC, wonowonow requested changes
코드 구현 잘해주셨습니다! 제가 코멘트 남긴 부분 수정 부탁드립니다

2023-12-28 14:39 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/comment/controller/CommentController.java
> +        CommentResponseDto commentResponseDto = Comment.toCommentResponse(member,
코멘트 엔티티를 컨트롤러 까지 끌고 오기보단 서비스 레이어에서 반환을 ResponseDto로 하면 좋을 거 같습니다.

2023-12-28 14:39 UTC, wonowonow commented on src/test/java/com/sparta/jamrello/domain/comment/service/CommentServiceTest.java
> +class CommentServiceTest {
클래스 명에 어떤 테스트인지 알려주는 게 좋을 거 같습니다

2023-12-28 14:39 UTC, wonowonow commented on src/test/java/com/sparta/jamrello/domain/comment/service/CommentServiceTest.java
> +    void test8() {
test 12345678 보다는 의미 있는 이름으로 바꾸고 똑같은 메서드 테스트의 경우 Nested로 묶는 것이 어떨까요?

2023-12-29 05:48 UTC, wonowonow commented on src/test/java/com/sparta/jamrello/domain/comment/service/CommentServiceTest.java
> +class CommentServiceTest {
Integration 붙여주시면 좋을 거 같습니당

2023-12-29 05:58 UTC, dmlal approved these changes
👍 👍

2023-12-29 05:58 UTC, dmlal commented on src/main/java/com/sparta/jamrello/domain/card/repository/CardRepository.java
> +@Repository
팁을 드리자면 Jpa레포지토리를 상속받는경우 @Repository 애너테이션은 안쓰셔도 됩니다.

2023-12-29 05:58 UTC, dmlal commented on src/main/java/com/sparta/jamrello/domain/comment/repository/CommentRepository.java
> +    @Query("SELECT c.member FROM Comment c WHERE c.id = :commentId")
궁금한게 있습니다!

간단한 쿼리문으로 보이는데 반드시 쿼리애너테이션을 사용해야할 이유가 있을까요??

2023-12-29 06:13 UTC, JungHyunMoon commented on src/main/java/com/sparta/jamrello/domain/comment/repository/CommentRepository.java
> +    @Query("SELECT c.member FROM Comment c WHERE c.id = :commentId")
처음에 member랑 조인해서 데이터를 가져올까하는 쿼리를 작성해서 만들려고 시작했는데
간단하게 끝나서 불필요하게 사용이 된거 같네요 리팩토링하겠습니다!

2023-12-29 06:36 UTC, JungHyunMoon commented on src/main/java/com/sparta/jamrello/domain/comment/controller/CommentController.java
> +        CommentResponseDto commentResponseDto = Comment.toCommentResponse(member,
이부분은 s3 업로드 구현하면서 같이 하겠습니다 ㅠ

2023-12-29 08:33 UTC, wonowonow approved these changes
![image](https://github.com/JamminTeam/Jamrello/assets/123870616/75dea802-8324-4805-834f-c6138634dc1e)

2023-12-29 08:34 UTC, merged