#20, #35 member 내 정보 수정, 회원 탈퇴 구현
JamminTeam/Jamrello pull request #38
Opened 2023-12-28 10:13 UTC by JunWoo0527

유저 기능 구현은 끝났고 테스트코드는 아직 완성하지 못해 완성한 기능부터 올렸습니다.

2023-12-28 14:18 UTC, wonowonow requested changes
제가 코멘트 남긴 부분 수정하시면 좋을 거 같습니다!

2023-12-28 14:18 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/member/controller/MemberController.java
>        @AuthenticationPrincipal UserDetailsImpl userDetails
@AuthUser 구현하셨으니까 이 부분 수정하시면 좋을 거 같습니다

2023-12-28 14:18 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/member/controller/MemberController.java
> +    List<FieldError> fieldErrors = bindingResult.getFieldErrors();
Valid 예외 처리하는 부분은 제가 전역 핸들러로 잡게끔 변경해놨습니다 이 부분 지우셔도 될 거 같습니다

2023-12-28 14:18 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/member/service/MemberServiceImpl.java
> +      UserDetailsImpl userDetails
UserDetails를 서비스 단위 까지 끌고 오신 이유가 있으신가요?
없으시다면 수정 부탁드립니다

2023-12-28 14:18 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/member/service/MemberServiceImpl.java
> +      UserDetailsImpl userDetails
![image](https://github.com/JamminTeam/Jamrello/assets/123870616/90ab9b73-3eb6-4a44-9fba-8cacd5fd9d7b)
정현님 코드 리뷰 했던 코멘트인데요 위 코멘트 참고 하시면 좋을 거 같습니다.
Url 때문에 MemberId를 두 번 쓰시는 게 마음에 안 드시는 거면
api/members/myInfo 이런 느낌으로 바꾸는 건 어떨까요? 남의 프로필 볼때만 memberId를 쓰구요

2023-12-28 14:18 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/member/service/MemberServiceImpl.java
> +  public void deleteMember(Long memberId, DeleteMemberRequestDto deleteMemberRequestDto, Member loginMember) {
이 부분도 위와 마찬가지로 Member를 끌고 오기보단 memberId를 끌고 오는 게 더 좋아보입니다, Url도 수정하시면 더 깔끔한 코드가 될 수 있을 거 같아요

2023-12-28 14:18 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/member/service/MemberServiceImpl.java
> +  private void sameMemberInDBByEmail(String email) {
변수명이 읽기가 어려워요 sameEmailInDB 라던지, existsEmail 이라는 메소드로 변경하시는 게 어떠실까요?

2023-12-29 02:17 UTC, JunWoo0527 commented on src/main/java/com/sparta/jamrello/domain/member/controller/MemberController.java
>        @AuthenticationPrincipal UserDetailsImpl userDetails
넵 반영했습니다.

2023-12-29 02:26 UTC, JunWoo0527 commented on src/main/java/com/sparta/jamrello/domain/member/controller/MemberController.java
> +    List<FieldError> fieldErrors = bindingResult.getFieldErrors();
넵 알겠습니다.

2023-12-29 02:29 UTC, JunWoo0527 commented on src/main/java/com/sparta/jamrello/domain/member/service/MemberServiceImpl.java
> +  public void deleteMember(Long memberId, DeleteMemberRequestDto deleteMemberRequestDto, Member loginMember) {
위에 같이 코멘트 남겼습니다.

2023-12-29 02:29 UTC, JunWoo0527 commented on src/main/java/com/sparta/jamrello/domain/member/service/MemberServiceImpl.java
> +      UserDetailsImpl userDetails
해당 UserDetails는 **@Authuser** 로 바뀌게되면서 Member 클래스로 바뀌어서 서비스단으로 넘어가는 로직으로 수정했습니다.  
또한 Member를 서비스단으로 직접가져온 이유는 현재 로직의 설계 목표가 타 회원 정보가 아닌 내 정보 수정을 위한 내 정보 보기만을 가정하고 설계하였고 이에 따라 내 정보는 내 자신만 수정 할 수 있어야 하기때문에 본인 여부 확인을 위해 서비스단에 해당 Member를 가져와서 username을 get하여 검증 하고있습니다. 물론 username자체로 넘겨줄수 있지만 제가 생각하기엔 컨트롤러에서는 받은 매개변수를 가공하지 않고 바로 서비스단에 넘기고 해당 가공을 서비스단에서 처리하는게 layer 분리 목적에 있다고 생각하여 이와 같이 처리 하였습니다. 
또한 다른 이유로는  추후 로직이 변경되어서 Member에  다른필드(password 등)으로 검증로직이 확장될때 또한 고려하여 Member클래스로 받아오고있습니다.

2023-12-29 06:08 UTC, dmlal approved these changes
👍 👍

2023-12-29 06:08 UTC, dmlal commented on src/main/java/com/sparta/jamrello/global/security/jwt/JwtAuthenticationFilter.java
> +        writer.println(" 403 : Bad Request");
Bad Request는 400입니다!

2023-12-29 11:52 UTC, closed without merging