#18 feat : S3 이미지업로드 구현
JamminTeam/Jamrello pull request #39
Opened 2023-12-28 13:22 UTC by dmlal

2023-12-28 14:37 UTC, JungHyunMoon commented
감사합니다 댓글 이미지 첨부에 유용하게 사용하도록 하겠습니다

2023-12-28 14:38 UTC, JungHyunMoon approved these changes

2023-12-28 14:50 UTC, wonowonow requested changes
기능 구현 잘해주셨습니다! 제가 코멘트 남긴 부분 리팩토링 해주시면 좋을 거 같습니다

2023-12-28 14:50 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/board/entity/Boards.java
> +  @ColumnDefault("false")
@ColumnDefault 보다, @Column(nullable=false) 해서 빌더 팩토리에서 false로 저장 되게끔 하는 게 더 좋아보입니다.

2023-12-28 14:50 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/board/entity/Boards.java
> +  public static Boards fromRequestDto(BoardRequestDto requestDto) {
createBoard라는 메서드명은 어떨까요?

2023-12-28 14:50 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/board/entity/Boards.java
> +public class Boards extends TimeStamp {
클래스명을 Boards로 하는 것보다 Board로 하는 게 좋아보입니다. Table 명은 어노테이션으로 수정이 되고, 저희 기능 구현 후 Table 명 단수로 수정하기로 했으니까요

2023-12-28 14:50 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/global/utils/s3/service/ImageUploadServiceImplV1.java
> +    Boards requestBoard = boardRepository.findById(boardId).orElseThrow(
중복되는 코드는 메서드로 빼는 게 좋아보입니다

2023-12-28 15:37 UTC, dmlal commented on src/main/java/com/sparta/jamrello/domain/board/entity/Boards.java
> +  public static Boards fromRequestDto(BoardRequestDto requestDto) {
단호히 거절하겠습니다

2023-12-29 01:12 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/board/entity/Boards.java
> +  public static Boards fromRequestDto(BoardRequestDto requestDto) {
ㅠㅠ

2023-12-29 01:16 UTC, dmlal commented on src/main/java/com/sparta/jamrello/domain/board/entity/Boards.java
> +public class Boards extends TimeStamp {
완

2023-12-29 01:16 UTC, dmlal commented on src/main/java/com/sparta/jamrello/domain/board/entity/Boards.java
> +  @ColumnDefault("false")
완

2023-12-29 01:21 UTC, dmlal commented on src/main/java/com/sparta/jamrello/global/utils/s3/service/ImageUploadServiceImplV1.java
> +    Boards requestBoard = boardRepository.findById(boardId).orElseThrow(
완

2023-12-29 01:29 UTC, wonowonow approved these changes
수고하셨습니다!

2023-12-29 01:29 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/global/utils/s3/service/ImageUploadServiceImplV1.java
> +    return requestBoard;
이부분은 CI/CD 구현했을 때, 리팩토링하면서 인라인으로 수정해주세요!

2023-12-29 02:52 UTC, merged