fix 브랜치내 머지오류로 브래친 변경 및 conflict 수정, #20, #35 member 내 정보 수정, 회원 탈퇴 구현
JamminTeam/Jamrello pull request #44
Opened 2023-12-29 11:49 UTC by JunWoo0527

브래친 오류로 인한 브래친 변경 및 코드리뷰 사항 conflict 수정 및 기능 구현

2023-12-30 04:45 UTC, wonowonow requested changes
수고하셨습니다! 제가 말씀드린 부분 수정해주시면 좋겠습니다!

2023-12-30 04:45 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/member/service/MemberServiceImpl.java
> +      throw new IllegalArgumentException("자신의 정보만 수정 할 수 있습니다.");
BisException을 던지는게 더 좋을 거 같아요

2023-12-30 04:45 UTC, wonowonow commented on src/main/java/com/sparta/jamrello/domain/member/service/MemberServiceImpl.java
> +    member.updateMember(updateMemberRequestDto, encodePassword);
인라인으로 줄일 수 있을 거 같아요

2023-12-31 02:52 UTC, JunWoo0527 commented on src/main/java/com/sparta/jamrello/domain/member/service/MemberServiceImpl.java
> +      throw new IllegalArgumentException("자신의 정보만 수정 할 수 있습니다.");
넵 수정하겠습니다.

2023-12-31 02:52 UTC, JunWoo0527 commented on src/main/java/com/sparta/jamrello/domain/member/service/MemberServiceImpl.java
> +    member.updateMember(updateMemberRequestDto, encodePassword);
넵 수정하겠습니다.

2023-12-31 04:24 UTC, wonowonow approved these changes
수고하셨습니다 !! 새해 복 많이 받으세요! 😀

2023-12-31 05:13 UTC, dmlal approved these changes
👍 👍 👍  수고하셨습니다!

2023-12-31 05:13 UTC, merged